### ISSUE TITLE
where is the slides?

### ISSUE THREAD

**Issue by pahaz** [PyCon/2016-slides#1]

**Comment by tedmiston** [comment]
Apparently there's a bug in Speaker Deck making them not visible.  Brian Costlow mentioned that on Twitter.

https://twitter.com/kicksopenminds/status/737873118149152768

As a workaround in the meantime, you can access several decks from Google's cache by copying a URL from here, then searching it prefaced by "cache:".

http://webcache.googleusercontent.com/search?client=safari&rls=en&q=cache:https://speakerdeck.com/pycon2016&ie=UTF-8&oe=UTF-8

**Comment by pahaz** [comment]
Thanks! But, I can see only two presentations. All others presentations are in processing state.

**Comment by wolever** [comment]
Apparently our account got flagged as spam by SpeakerDeck and unfortunately it took a couple of days to resolve. Brian's started the process of uploading them again now, and they should all be available within a day or two.
